version: "3.8"
services:
    app:
        build:
            args:
                user: philipe
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: imagembase
        container_name: container-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./..:/var/www
            - ./docker-compose/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        networks:
            - conexao_discada

    nginx:
        image: nginx:alpine
        container_name: container-web
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./..:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - conexao_discada
        links:
            - app
    db:
        image: postgres:13-alpine
        restart: unless-stopped
        container_name: container-db
        environment:
            POSTGRES_PASSWORD: policiateste
        ports:
            - "5432:5432"
        volumes:
            - /home/philipe/postgresdb:/var/lib/postgresql/data
        networks:
            - conexao_discada

networks:
    conexao_discada:
        driver: bridge
